import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import test from "node:test";
import { evaluateMath, evaluateMathResult, parseDimension, parseDimensionResult, substituteVariables, withMathDiagnostics } from "../src/engine/math.js";
import { evaluateRestrictedExpression, MathExpressionError, MATH_EXPRESSION_LIMITS } from "../src/engine/safe-expression.js";
import { evaluateAxisExpression, evaluateAxisExpressionAtSample, evaluateAxisExpressionResult, parsePgfplotsDeclaredFunctions } from "../src/pgfplots/expressions.js";
import { createForeachBudget, expandForeachValues, foreachIterationVariables, ForeachExpansionError, FOREACH_EXPANSION_LIMIT } from "../src/tikz/commands/foreach.js";

test("restricted maths reject host access, calls, assignment, and non-math syntax", () => {
  const attacks = [
    "globalThis.tikzAuditFlag=29", "{globalThis.tikzAuditFlag=29}",
    "globalThis", "process.exit()", "Math.random()", "Math.PI", "sin.constructor(1)",
    "constructor(1)", "toString()", "__proto__", "[].constructor", "x[0]", "x=4", "x+=1",
    "(()=>1)()", "function(){return 1}", "new Date()", "import(1)", "1;2", "1,2",
    "1/* comment */+2", "1//comment", "`template`", "'text'", "0?1:x=2"
  ];
  const before = globalThis.tikzAuditFlag;
  for (const expression of attacks) {
    for (const result of [evaluateMathResult(expression), evaluateAxisExpressionResult(expression, 0)]) {
      assert.equal(result.ok, false, expression);
      assert.ok(Number.isNaN(result.value), expression);
      assert.equal(result.diagnostic.severity, "error");
      assert.equal(result.diagnostic.expression, expression);
    }
  }
  assert.equal(globalThis.tikzAuditFlag, before);
});

test("math variables are data, not host callbacks or inherited properties", () => {
  let called = 0;
  const variables = Object.create({ inherited: 3 });
  Object.defineProperty(variables, "getter", { enumerable: true, get() { called += 1; return 4; } });
  variables.callback = () => { called += 1; return 1; };
  variables.object = { valueOf() { called += 1; return 1; }, toString() { called += 1; return "1"; } };
  for (const expression of ["inherited", "getter", "callback()", "object"]) {
    assert.equal(evaluateRestrictedExpression(expression, variables).ok, false);
    assert.equal(evaluateAxisExpressionResult(expression, 0, {}, variables).ok, false);
  }
  assert.ok(Number.isNaN(evaluateMath(String.raw`\object`, variables)));
  assert.ok(Number.isNaN(evaluateMath(String.raw`\getter`, variables)));
  assert.equal(called, 0);
  assert.equal(evaluateMathResult(String.raw`\x`, { x: "globalThis.tikzAuditFlag=29" }).ok, false);
});

test("R5 invalid coordinates stay failures with the original source expression", () => {
  for (const expression of ["sqrt(-1)", "1/0", String.raw`\doesnotexist`, String.raw`\ctikzvalof{unknown/key}`, "", "2+", "1e999"]) {
    assert.ok(Number.isNaN(evaluateMath(expression)), expression);
    assert.ok(Number.isNaN(parseDimension(expression)), expression);
    const result = parseDimensionResult(expression);
    assert.equal(result.ok, false);
    assert.equal(result.diagnostic.expression, expression);
  }
  assert.equal(evaluateMathResult("0").value, 0);
  assert.equal(parseDimensionResult("0cm").value, 0);
  assert.equal(parseDimension(0), 0);
  assert.equal(substituteVariables(String.raw`\missing`), String.raw`\missing`);
  assert.equal(evaluateMathResult("sqrt(-1)").diagnostic.code, "math-nonfinite");
  assert.equal(evaluateMathResult(String.raw`\missing`).diagnostic.code, "math-unknown-variable");
});

test("diagnostic hooks are scoped, restored on throw, and support parent failure policies", () => {
  const outer = [], inner = [], explicit = [];
  withMathDiagnostics(outer, () => {
    evaluateMath("sqrt(-1)");
    assert.throws(() => withMathDiagnostics(inner, () => parseDimension("1/0", {}, { throwOnError: true })), MathExpressionError);
    evaluateMath(String.raw`\missing`);
    evaluateAxisExpression("nope(x)", 0, {}, {}, { diagnostics: explicit });
  });
  evaluateMath("1/0");
  assert.deepEqual(outer.map((entry) => entry.expression), ["sqrt(-1)", String.raw`\missing`]);
  assert.deepEqual(inner.map((entry) => entry.expression), ["1/0"]);
  assert.deepEqual(explicit.map((entry) => entry.expression), ["nope(x)"]);
});

// Values captured from the audited HEAD evaluator, not JavaScript generated by
// the test. In particular, PGF's fixed-point trig table is not native Math.sin.
const baselineCases = [
  ["2+3*4", 14], ["-2^2", -4], ["(-2)^2", 4], ["2^3^2", 512], ["2^-2", 0.25],
  ["1<2?3:4", 3], ["0?2:3?4:5", 4], ["1&&2", 2], ["0||7", 7], ["5&3", 1], ["5|2", 7],
  ["1e-3+2E2", 200.001], ["pow(2,3)", 8], ["sinh(2)", 3.626860407847019], ["cosh(2)", 3.7621956910836314],
  ["floor(-2.4)", -3], ["ceil(-2.4)", -2], ["round(-2.5)", -2], ["sign(-2)", -1],
  ["rad(180)", Math.PI], ["deg(pi)", 180], ["asin(.5)", 30.000000000000004], ["acos(.5)", 60.00000000000001],
  ["atan(1)", 45], ["atan2(1,-1)", 135], ["veclen(3,4)", 5], ["ifthenelse(0,2,3)", 3],
  ["greater(2,1)", 1], ["less(1,2)", 1], ["equal(.1+.2,.3)", 1], ["not(0)", 1],
  ["and(2,3)", 1], ["or(0,2)", 1], ["div(-7,3)", -2], ["mod(-7,3)", -1], ["Mod(-7,3)", 2],
  ["50*sin(1/50)", 0.017], ["sin(48.294)", 0.74652], ["cos(-390.34)", 0.86301], ["tan(48.294)", 1.122114],
  ["x*y*y/(x*x+y*y*y*y)", 0], ["gauss(0,1)", 0.3989422804014327]
];

test("PGF operators and runtime prelude functions retain audited differential values", () => {
  for (const [expression, expected] of baselineCases) assert.equal(evaluateAxisExpression(expression, 0, {}, { y: 0 }), expected, expression);
  for (const [expression, expected] of [["1--2", 3], ["1++2", 3], ["int(-2.8)", -2], ["mod(-5,3)", 1], ["Mod(-5,3)", 1]]) {
    assert.equal(evaluateMath(expression), expected, expression);
  }
  assert.ok(Math.abs(evaluateMath("gamma(5)") - 24) < 1e-12);
  assert.equal(evaluateMath("sin(30)"), Math.sin(Math.PI / 6));
  assert.equal(evaluateMath(String.raw`2*\scale+\offset`, { scale: 3, offset: 1 }), 7);
  assert.equal(parseDimension(String.raw`0.35\textwidth`, { textwidth: 10 }), 3.5);
  assert.equal(parseDimension("{2cm+3mm}"), 2.3);
  assert.equal(evaluateMath(String.raw`\ctikzvalof{tubes/width}`), 1);
});

test("nested powers, ternaries and per-call radians are parsed with mathematical precedence", () => {
  assert.equal(evaluateMath("-((2+3)*2)^2"), -100);
  assert.equal(evaluateMath("{{2+(3*4)}}"), 14);
  assert.equal(evaluateMath("0?1/0:3"), 3);
  assert.equal(evaluateMath("1?2:unknown()"), 2);
  assert.equal(evaluateMath("ifthenelse(0,1/0,5)"), 5);
  assert.equal(evaluateMath("0&&(1/0)"), 0);
  assert.equal(evaluateMath("1||(1/0)"), 1);
  assert.equal(evaluateAxisExpression("sin((x*x)r)+cos(0)", Math.sqrt(Math.PI / 2)), 2);
  assert.equal(evaluateAxisExpression("sin(x)", Math.PI / 2, { "trig format": "rad" }), 1);
  assert.equal(evaluateAxisExpression("sin(deg(pi/2))", 0), 1);
  assert.ok(Math.abs(evaluateMath("sin((sqrt(4)*pi/4)r)") - 1) < 1e-12);
  assert.equal(evaluateMathResult("sin(30 bogus)").diagnostic.code, "math-syntax");
  for (const source of ["sin()", "sin(1,2)", "pow(2)", "min()", "ifthenelse(1,2)"]) {
    assert.equal(evaluateAxisExpressionResult(source, 0).diagnostic.code, "math-arity");
  }
});

test("declared functions and variable values use bounded ASTs and numeric local bindings", () => {
  const declarations = parsePgfplotsDeclaredFunctions(String.raw`mu=2; sigma=3; f(\x)=\x^2; g(\x,\y)=f(\x)+\y+mu+sigma; h()=7`);
  const options = { "pgfplots declared functions": declarations };
  assert.equal(evaluateAxisExpression("f(x)+g(x,2)+h()", 3, options), 32);
  assert.equal(evaluateAxisExpression(String.raw`\x+\y`, 2, {}, { y: "2+3" }), 7);
  for (const source of ["f(x)=f(x)+f(x)", "a=b;b=a", "f(x)=g(x);g(x)=f(x)"]) {
    const opts = { "pgfplots declared functions": parsePgfplotsDeclaredFunctions(source) };
    const result = evaluateAxisExpressionResult(source.startsWith("a=") ? "a" : "f(x)", 1, opts);
    assert.equal(result.ok, false);
    assert.equal(result.diagnostic.code, "math-expression-limit");
  }
  assert.equal(evaluateRestrictedExpression("x", { x: "y", y: "x" }).diagnostic.code, "math-expression-limit");
  const attack = { "pgfplots declared functions": parsePgfplotsDeclaredFunctions("f(x)=globalThis.tikzAuditFlag=29") };
  assert.equal(evaluateAxisExpressionResult("f(x)", 0, attack).ok, false);
});

test("expression source, nesting, token and evaluation budgets fail without stack overflow", () => {
  for (const expression of [
    "1".repeat(MATH_EXPRESSION_LIMITS.characters + 1),
    "(".repeat(2000) + "1" + ")".repeat(2000),
    "-".repeat(2000) + "1", "2^".repeat(2000) + "2",
    "1*".repeat(MATH_EXPRESSION_LIMITS.tokens) + "1"
  ]) {
    assert.equal(evaluateMathResult(expression).diagnostic.code, "math-expression-limit");
  }
  assert.equal(evaluateMath("2+2"), 4, "a failed parse cannot poison subsequent evaluations");
  const variables = { x: "1+".repeat(1000) + "1" };
  const expanded = String.raw`\x+`.repeat(100) + "1";
  assert.equal(evaluateMathResult(expanded, variables).diagnostic.code, "math-expression-limit");
  assert.equal(parseDimensionResult(expanded, variables).diagnostic.code, "math-expression-limit");
});

test("PGFPlots retains isolated singular recovery without zeroing other invalid maths", () => {
  assert.equal(evaluateAxisExpression("x*y*y/(x*x+y*y*y*y)", 0, {}, { y: 0 }), 0);
  assert.ok(Number.isNaN(evaluateMath("0/0")));
  assert.ok(Number.isNaN(evaluateAxisExpression("sqrt(-1)", 0)));
  assert.ok(Number.isNaN(evaluateAxisExpression("1/0", 0)));
  const diagnostics = [];
  assert.equal(withMathDiagnostics(diagnostics, () => evaluateAxisExpressionAtSample("-x*ln(x)", 0, {}, { domain: { start: 0, end: 1 }, index: 0, samples: 11 })), 0);
  assert.deepEqual(diagnostics, []);
});

test("R2 foreach rejects zero/nonfinite steps and oversized ranges with structured errors", () => {
  const badRanges = [["1", "1", "...", "3"], ["1e999", "...", "3"], ["0", "...", "1e300"], ["1", "...", "1/0"], ["0", "...", String.raw`\missing`]];
  for (const values of badRanges) {
    assert.throws(() => expandForeachValues(values), (error) => {
      assert.ok(error instanceof ForeachExpansionError || error instanceof MathExpressionError);
      assert.equal(error.diagnostic.severity, "error");
      assert.ok(error.diagnostic.expression);
      return true;
    });
  }
  assert.throws(() => expandForeachValues(["1", "1", "...", "3"]), { code: "foreach-nonprogressing-range" });
  assert.throws(() => expandForeachValues(["0", "...", String(FOREACH_EXPANSION_LIMIT)]), { code: "foreach-expansion-limit" });
});

test("foreach list, descending and fractional ranges retain values and share nested/sibling budgets", () => {
  assert.deepEqual(expandForeachValues([0, "...", "3"]), ["0", "1", "2", "3"]);
  assert.deepEqual(expandForeachValues(["3", "2", "...", "0"]), ["3", "2", "1", "0"]);
  assert.deepEqual(expandForeachValues(["3", "...", "1"]), ["3", "2", "1"]);
  assert.deepEqual(expandForeachValues(["0", "0.1", "...", "0.3"]), ["0", "0.1", "0.2", "0.3"]);
  const env = { variables: { items: "a,b,c" }, foreachBudget: createForeachBudget({ maxIterations: 5 }) };
  assert.deepEqual(expandForeachValues([String.raw`\items`], env), ["a", "b", "c"]);
  const child = { ...env, variables: {} };
  assert.deepEqual(expandForeachValues(["1", "2"], child), ["1", "2"]);
  assert.throws(() => expandForeachValues(["3"], env), { code: "foreach-expansion-limit" });
  assert.throws(() => expandForeachValues(["abcd"], { foreachBudget: createForeachBudget({ maxCharacters: 3 }) }), { code: "foreach-expansion-limit" });
});

test("foreach count/evaluate options preserve valid values and reject invalid maths", () => {
  const statement = { variables: ["x"], values: ["1", "2"], options: { count: String.raw`\i from 0`, evaluate: String.raw`\x as \y using \x^2` } };
  assert.deepEqual(foreachIterationVariables(statement).map(({ variables }) => variables), [{ x: "1", i: 0, y: 1 }, { x: "2", i: 1, y: 4 }]);
  assert.throws(() => foreachIterationVariables({ ...statement, options: { count: String.raw`\i from sqrt(-1)` } }), MathExpressionError);
  assert.throws(() => foreachIterationVariables({ ...statement, options: { evaluate: String.raw`\x as \y using 1/0` } }), MathExpressionError);
});

test("math helpers and representative rendering work when string code generation is disabled", () => {
  const script = `
    import assert from 'node:assert/strict';
    import { evaluateMath } from './src/engine/math.js';
    import { evaluateAxisExpression } from './src/pgfplots/expressions.js';
    import { tikzToSvg } from './src/index.js';
    assert.equal(evaluateMath('sqrt(4)+sin(90)'), 3);
    assert.equal(evaluateAxisExpression('50*sin(1/50)', 0), 0.017);
    const result = tikzToSvg(String.raw\`\\begin{tikzpicture}\\draw ({sqrt(4)},0) -- (1,1);\\end{tikzpicture}\`);
    assert.equal(result.ok, true);
    assert.match(result.svg, /<path/);
    const plot = tikzToSvg(String.raw\`\\begin{tikzpicture}\\begin{axis}[samples=3,domain=0:2]\\addplot {x^2};\\end{axis}\\end{tikzpicture}\`);
    assert.equal(plot.ok, true);
    assert.match(plot.svg, /<path/);
  `;
  const result = spawnSync(process.execPath, ["--disallow-code-generation-from-strings", "--input-type=module", "-e", script], { cwd: new URL("..", import.meta.url), encoding: "utf8", timeout: 10000 });
  assert.equal(result.status, 0, result.stderr || result.error?.message);
});
