export const tikzLibrary = {
  name: "datavisualization",
  status: "partial",
  category: "datavisualization",
  implementedBy: "src/frontend/latex-shell.js:expandDatavisualizationFunctions/datavisualizationScreenSpacePinLayout + src/engine/evaluate.js:estimateNodeSize + src/renderers/svg/richTextNode.js",
  localSource: "/usr/local/texlive/2025/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/datavisualization/tikzlibrarydatavisualization.code.tex",
  localDoc: "/usr/local/texlive/2025/texmf-dist/doc/generic/pgf/pgfmanual-en-dv-visualizers.tex",
  localSourceReviewed: "yes",
  features: [
    "basic scientific axes lowering",
    "table data blocks with x/y/set columns",
    "named visualizers via visualize as line, smooth line, smooth cycle, and scatter",
    "native scatter mark=x diagonal sizing from mark size / sqrt(2)",
    "data point set routing across multiple visualizers",
    "visualizer style, label in legend, straight label in legend line, no lines mark-only mode, straight cycle, smooth cycle, gap line, gap cycle, and polygon alias",
    "global legend entry options/default label in legend path/.style=straight label in legend line for line legend samples",
    "native-like school-book axes default outside line legend placement",
    "focused inside legend placement, data-value legend anchors, opaque legend matrix backgrounds, and label style=text only",
    "explicit legend anchor/at placement for data visualization bounding box anchors",
    "focused legend at-coordinate projections using |- and -|",
    "focused legend label node style draw/circle routing through datavis legend entry node style",
    "compact native-style TeX box metrics for styled inline-math legend labels without changing SVG math paint",
    "south east outside scatter legend matrix anchoring from data-bounding-box dimensions and native em offsets",
    "mixed prose/math legend labels with explicit west/end SVG anchoring and surrounding-text inline math sizing",
    "pin in data auto placement from the preceding canvas segment with TeX node padding and clipped leader edges",
    "style sheet=strong colors, vary hue, vary dashing, vary thickness, and vary thickness and dashing for line visualizers",
    "default outside line legend samples positioned by native physical em offsets from the data area",
    "custom /pgf/data visualization/style sheets/<name>/<value>/.style definitions for set-based plot styling",
    "\\tikzdatavisualizationset named styles for focused datavis option bundles",
    "/data point/set/.style sheet=<name> key handler as an alias for set-attached style sheets",
    "\\pgfdvdeclarestylesheet{<name>}{...} declarations for focused custom style sheets",
    "\\tikzdvdeclarestylesheetcolorseries{<name>}{hsb|rgb}{<start>}{<step>} declarations for set-attached color-series style sheets",
    "/data point/set/<name>/.initial=<value> remapping before style sheet lookup",
    "built-in scatter mark style sheets * mark, dot mark, and o mark",
    "explicit data point [x=..., y=..., set=...] streams",
    "data [format=named] attribute assignments with list and range cartesian expansion",
    "data groups containing explicit data point streams",
    "school book axes lowering with native asymmetric x/y origin tick labels",
    "nested scientific axes styles including clean and end labels",
    "Cartesian x/y axis attribute mapping for numeric point attributes",
    "linear Cartesian axis scaling via scaling=<source> at <target> and <source> at <target>",
    "x/y axis label lowering with standard, upright, and end placement",
    "x/y/all axes grid, length, min value, max value, include value, and simple tick controls",
    "focused xy Cartesian visualize ticks low/high/style/direction axis tick marks plus tick text at low/high endpoint labels",
    "visualizer options/ignore style sheets without consuming style sequence slots"
  ],
  notes:
    "Implemented through the same focused preprocessor as datavisualization.formats.functions. Reviewed locally through 2026-09-06 against tikzlibrarydatavisualization.code.tex, pgfmoduledatavisualization.code.tex, tikz.code.tex, and pgfmanual-en-dv-visualizers.tex. Explicit south-east outside scatter legends use the source's data-bounding-box anchor with physical .8em/.5em/.333em offsets. Browser mixed prose/math legend labels honor their west anchor and keep inline math at the prose size. Pin labels use the PGF label visualizer's current/previous canvas positions, the default 3ex distance, auto-node padding, and a leader clipped to the label border. The school-book axis slice retains x=0 label suppression and a north-east y=0 label. Custom pgfooclass visualizers and exact arbitrary matrix legends remain partial. Evidence: docs/qa/2026-09-06-datavisualization-pin-scatter.md."
};
