export const tikzLibrary = {
  name: "datavisualization",
  status: "partial",
  category: "datavisualization",
  implementedBy: "src/frontend/latex-shell.js:expandDatavisualizationFunctions",
  features: [
    "basic scientific axes lowering",
    "table data blocks with x/y/set columns",
    "named visualizers via visualize as line, smooth line, smooth cycle, and scatter",
    "native scatter mark=x diagonal sizing from mark size / sqrt(2)",
    "data point set routing across multiple visualizers",
    "visualizer style, label in legend, straight label in legend line, no lines mark-only mode, straight cycle, smooth cycle, gap line, gap cycle, and polygon alias",
    "global legend entry options/default label in legend path/.style=straight label in legend line for line legend samples",
    "native-like school-book axes default outside line legend placement",
    "focused inside legend placement, data-value legend anchors, opaque legend matrix backgrounds, and label style=text only",
    "explicit legend anchor/at placement for data visualization bounding box anchors",
    "focused legend at-coordinate projections using |- and -|",
    "focused legend label node style draw/circle routing through datavis legend entry node style",
    "style sheet=strong colors, vary hue, vary dashing, vary thickness, and vary thickness and dashing for line visualizers",
    "default outside line legend samples positioned by native physical em offsets from the data area",
    "custom /pgf/data visualization/style sheets/<name>/<value>/.style definitions for set-based plot styling",
    "\\tikzdatavisualizationset named styles for focused datavis option bundles",
    "/data point/set/.style sheet=<name> key handler as an alias for set-attached style sheets",
    "\\pgfdvdeclarestylesheet{<name>}{...} declarations for focused custom style sheets",
    "\\tikzdvdeclarestylesheetcolorseries{<name>}{hsb|rgb}{<start>}{<step>} declarations for set-attached color-series style sheets",
    "/data point/set/<name>/.initial=<value> remapping before style sheet lookup",
    "built-in scatter mark style sheets * mark, dot mark, and o mark",
    "explicit data point [x=..., y=..., set=...] streams",
    "data [format=named] attribute assignments with list and range cartesian expansion",
    "data groups containing explicit data point streams",
    "school book axes lowering",
    "nested scientific axes styles including clean and end labels",
    "Cartesian x/y axis attribute mapping for numeric point attributes",
    "linear Cartesian axis scaling via scaling=<source> at <target> and <source> at <target>",
    "x/y axis label lowering with standard, upright, and end placement",
    "x/y/all axes grid, length, min value, max value, include value, and simple tick controls",
    "focused xy Cartesian visualize ticks low/high/style/direction axis tick marks plus tick text at low/high endpoint labels",
    "visualizer options/ignore style sheets without consuming style sequence slots"
  ],
  notes:
    "Implemented through the same focused preprocessor as datavisualization.formats.functions. This covers common manual Chapter 83 visualizers but not the full PGF data visualization object/survey pipeline or custom pgfooclass visualizers."
};
