export const tikzLibrary = {
  "name": "trees",
  "status": "partial",
  "implementedBy": "src/frontend/parser.js:parseNodeTreeChild/parseNodeTreeForeach + src/engine/evaluate.js:createNodeTreeChildren/expandTreeChildForeach/mergeTreeGrowthOptions/treeGrowthSpec/treeChildOffset/treeGrowthParentPoint/treeEdgeEndpoints/treeEveryChildNodeOptions + src/tikz/commands/foreach.js:foreachIterationVariables",
  "localSourceReviewed": "yes",
  "localSource": "/usr/local/texlive/2025/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarytrees.code.tex",
  "localDoc": "/usr/local/texlive/2025/texmf-dist/doc/generic/pgf/pgfmanual-en-tikz-trees.tex",
  "notes": "Reviewed locally on 2026-08-07 against the trees source and manual. Child placement starts from `growth parent anchor`; `every child node` is merged before each generated child node; parent/child anchors select the endpoints of the generated edge, with `border` retaining automatic node-border clipping. The four documented fork routes use those same anchors. Reviewed again on 2026-09-05 against tikz.code.tex lines 4550-4677 and the manual's Missing Children section: bare and bodied `child[missing]` entries count toward sibling totals and indices but emit no coordinate, node, parent edge, body, or descendants; a child-local `missing=false` overrides inherited `every child` missing state. Reviewed on 2026-09-05 against tikz.code.tex lines 4544-4677, pgffor.code.tex, and the manual's child foreach examples: `child foreach` is expanded before sibling totals and positions are computed, slash-separated values bind slash-separated variables in local iteration scope, and nested child loops inherit outer bindings. Reviewed on 2026-09-05 against tikz.code.tex lines 1380-1395 and 4639-4677 plus the manual's Default Growth Function section: `grow'` preserves the main growth angle and swaps the two orthogonal sibling angles; named and numeric directions use all children in the native total/current index; a child-local `grow` or `grow'` suppresses only its current-level sibling displacement and remains active for descendants. Graph drawing, arbitrary edge-from-parent paths, custom growth functions, and collision-avoiding tree layouts remain partial.",
  "features": [
    "node child trees",
    "grow direction",
    "grow prime mirrored sibling order",
    "numeric grow angles with orthogonal sibling spacing",
    "cardinal and diagonal grow direction aliases",
    "child-local grow special-level placement and descendant inheritance",
    "grow cyclic",
    "level distance",
    "sibling distance",
    "sibling angle",
    "growth parent anchor",
    "every child node",
    "parent anchor and child anchor tree edges",
    "edge from parent fork down/up/left/right",
    "clockwise/counterclockwise from",
    "missing child sibling-slot occupancy",
    "bare and bodied missing children",
    "missing=false override of every child",
    "child foreach expansion before sibling layout",
    "slash-separated child foreach variables and values",
    "nested child foreach with outer-variable inheritance",
    "picture-level stroke style inheritance for generated child edges",
    "focused TCS logo macro expansion"
  ],
  "implements": [
    "node child trees",
    "grow direction",
    "grow prime mirrored sibling order",
    "numeric grow angles with orthogonal sibling spacing",
    "cardinal and diagonal grow direction aliases",
    "child-local grow special-level placement and descendant inheritance",
    "grow cyclic",
    "level distance",
    "sibling distance",
    "sibling angle",
    "growth parent anchor",
    "every child node",
    "parent anchor and child anchor tree edges",
    "edge from parent fork down/up/left/right",
    "clockwise/counterclockwise from",
    "missing child sibling-slot occupancy",
    "bare and bodied missing children",
    "missing=false override of every child",
    "child foreach expansion before sibling layout",
    "slash-separated child foreach variables and values",
    "nested child foreach with outer-variable inheritance",
    "picture-level stroke style inheritance for generated child edges",
    "focused TCS logo macro expansion"
  ]
};
