export const circuitikzFontRoles = Object.freeze({
  label: "label",
  annotation: "annotation",
  tiny: "tinySymbol",
  sixPoint: "sixPointSymbol",
  normal: "normalSymbol",
  large: "largeSymbol"
});

export const texPackage = {
  "name": "circuitikz",
  "status": "partial",
  "implementedBy": "src/engine/evaluate.js:appendCircuitikzToSegment/circuitikzVoltageSourceItems/circuitikzCurrentSourceItems/circuitikzDcCurrentAngle/circuitikzComponentFill/circuitikzWaveformSourceItems/circuitikzWaveformSymbolItem/circuitikzSourceSymbolRotation/circuitikzSourceScale/circuitikzDiamondPath/circuitikzVoltageSourceSymbolNodes/appendCircuitikzVoltageLabel/appendCircuitikzAmericanSinusoidalVoltagePolarity/circuitikzBatteryItems/circuitikzBatteryScale/circuitikzInductorSettings/circuitikzInductorItems/circuitikzChokeCoreItems/circuitikzTransformerCoreSettings/circuitikzDiodeSpec/circuitikzDiodeSettings/circuitikzDiodeItems/circuitikzZenerCathodeCommands/circuitikzZzenerCathodeCommands/circuitikzTvsCathodeCommands/circuitikzDiodeWhiskers/circuitikzLedArrowItems/circuitikzPhotodiodeArrowItems/circuitikzLaserArrowItems/circuitikzOptoArrowStyle/circuitikzOptoArrowDirection/normalizeCtikzSetOptions/registerCircuitikzInductorNode;src/renderers/svg/circuitikzNodes.js:renderCircuitikzTransformerBody/renderCircuitikzTransformerCore",
  "features": [
    "short wires",
    "R/C/basic independent current and voltage source slices",
    "D/D*/Do, zD/zD*/zDo, zzD/zzD*/zzD-, sD/sD*, leD/leD*, pD/pD*/pDo, lasD/lasD*/lasDo, and tvsD/tvsD*/tvsDo diode bipoles with diodes/scale, diodes/fill, l= labels, horizontal/vertical placement, optical-arrow direction/color/thickness, and straight/sloped Zener/TVS whiskers",
    "DC dcvsource/dcisource sources with fill and bipoles/dcisource/angle",
    "controlled cV/cI diamond sources in European and American styles with csources/scale",
    "controlled sinusoidal csV/csI sources with exact PGF sine/cosine cubics, csources/scale, csources/symbol/thickness, csources/symbol/rotate, and American external csV polarity markers",
    "independent sV/sI sinusoidal sources with exact PGF sine/cosine cubics, sources/scale, sources/symbol/thickness, sources/symbol/rotate, bipoles/isourcesin/angle, and American external sV polarity markers",
    "independent square/triangle voltage sources sqV/tV with documented aliases and waveform-symbol rotation",
    "battery, battery1, and battery2 plate families with batteries/scale",
    "american voltage-source circle with internal + and - polarity symbols, including backward V< direction",
    "L/vL cute, American, and European inductor slice with scale/width/coils",
    "cute choke single/double core lines with cthick",
    "named inductor core west/east anchors with configurable core distance",
    "default cute transformer bodies with source-derived half-elliptical coils, lead geometry, and core styling",
    "terminal markers",
    "op amp and tube node subset",
    "package option siunitx: normalize \\SI and circuitikz angle-unit labels",
    "package option RPvoltages: set reference-polarity direction for American +/- and European arrow voltage notation"
  ],
  "requires": [],
  "localSource": "/usr/local/texlive/2025/texmf-dist/tex/latex/circuitikz/circuitikz.sty",
  "localDoc": "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.pdf",
  "localSourceReviewed": [
    "/usr/local/texlive/2025/texmf-dist/tex/latex/circuitikz/circuitikz.sty (circuitikz environment aliases tikzpicture, line 400)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircbipoles.tex (resistor defaults and american/european independent voltage-source geometry, lines 32-113 and 2280-2372)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircvoltage.tex (V< direction plus the generic American external voltage-label routine, lines 318-361 and 411-437)",
    "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.tex (RPvoltages semantics and american source selection, lines 435, 2921-2930, 3177-3198, 8942-9176)",
    "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.tex (Inductors customizations and anchors, lines 2539-2685)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircbipoles.tex (inductor, choke, and core-anchor path geometry, lines 1286-1906)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcirc.defines.tex (csources scale-class geometry, lines 694-798 and 1058-1064)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircbipoles.tex (controlled voltage/current source diamond paths and aliases, lines 3404-3586 and 3824-3998)",
    "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.tex (controlled source defaults and csources/scale, lines 2950-2970 and 3125-3130)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcirc.defines.tex (batteries scale-class dimensions and defaults, lines 694-800 and 1054-1056)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircbipoles.tex (battery/battery1/battery2 plate, connector, and line-width geometry, lines 1959-1964 and 2095-2201)",
    "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.tex (battery class and supported battery types, lines 2902-2914)",
    "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.tex (independent sinusoidal sV/sI sources and open-current example, lines 2928-2947)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcirc.defines.tex (sources scale class, lines 1058-1061)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircbipoles.tex (source symbol thickness/rotation defaults, sV waveform, sI open outline, and aliases, lines 1937-1975, 2270-2278, 2384-2407, 3353-3383, and 3849-3952)",
    "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.tex (controlled sinusoidal aliases and dependent symbol-thickness class, lines 2970-2971 and 3157-3159)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircbipoles.tex (controlled sinusoidal diamond/wave geometry and aliases, lines 3454-3520 and 3855-3860, 3949-3953)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.code.tex (exact \\pgfpathsine/\\pgfpathcosine cubic controls used by circuitikz source waves, lines 1321-1368)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcirc.defines.tex (American plus/minus glyphs and voltage-label distances, lines 1211 and 1260-1270)",
    "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.tex (waveform thickness and local/auto rotation semantics, lines 3156-3172)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircbipoles.tex (sources/csources rotation defaults and square/triangle wave paths, lines 1971-1975, 2270-2278, 2409-2454, and 3849-3872)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircquadpoles.tex (transformer-core defaults, choke-thickness multiplier, color/dash subset, and transformer L1/L2 lead routing, lines 20-32 and 205-329)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircbipoles.tex (cuteinductor default dimensions plus alternating wide/return half-ellipse construction, lines 1286-1306 and 1406-1432)",
    "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.tex (transformer-core style directory, default/inherit/none dash semantics, and customization example, lines 5949-5968 and 6100-6124)",
    "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.tex (DC voltage/current source example and dcisource angle setting, lines 3108-3123)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircbipoles.tex (dcvsource plates plus dcisource fill/open-arc/arrow geometry, lines 1923-1927 and 2537-2585)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircshapes.tex (currarrow outline geometry and current-arrow scale, lines 413-450)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcirc.defines.tex (diode scale-class dimensions/defaults and diodes/scale/fill keys, lines 694-798 and 1038-1040)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircbipoles.tex (basic diode triangle/bar, Schottky hook, and LED latexslim-arrow geometry, lines 2920-3260)",
    "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.tex (D*/Do/D- and sD*/leD* aliases plus diode customization keys, lines 1642-1648 and 2674-2727)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircbipoles.tex (Zener, ZZener, and TVS full/empty/stroke paths plus straight/sloped whisker switch, lines 4069-4074, 4141-4191, 4424-4478, and 4622-4679)",
    "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.tex (zD/zzD/tvsD aliases and diode straight/sloped whiskers, lines 2680-2730 and 2890-2901)",
    "/usr/local/texlive/2025/texmf-dist/tex/generic/circuitikz/pgfcircbipoles.tex (LED/photodiode flip booleans, photodiode/laser optical-arrow paths, double laser cathode, and full/empty aliases, lines 4076-4093, 4244-4279, 4316-4360, 4539-4585, and 5177-5180)",
    "/usr/local/texlive/2025/texmf-dist/doc/latex/circuitikz/circuitikzmanual.tex (documented pD/lasD forms, pd arrow direction, and opto arrow color/relative-thickness keys, lines 2676-2730 and 2824-2875)"
  ],
  "caseCount": 488,
  "caseExamples": [
    "Tikzquads quadripoles and load line",
    "seebeck effect",
    "circuitikz manual snippet 001",
    "circuitikz manual snippet 002",
    "circuitikz manual snippet 003",
    "circuitikz manual snippet 004",
    "circuitikz manual snippet 005",
    "circuitikz manual snippet 006",
    "circuitikz manual snippet 007",
    "circuitikz manual snippet 008",
    "circuitikz manual snippet 009",
    "circuitikz manual snippet 010",
    "circuitikz inductors",
    "circuitikz chokes and core anchors",
    "circuitikz basic bipoles",
    "circuitikz battery plate families",
    "circuitikz DC voltage and current sources",
    "circuitikz independent sinusoidal voltage and current sources",
    "circuitikz controlled sinusoidal voltage and current sources",
    "circuitikz waveform symbols with local and automatic rotation",
    "circuitikz transformer core customization",
    "circuitikz diode, Schottky, and LED bipoles",
    "circuitikz Zener, ZZener, and TVS diode whiskers",
    "circuitikz photodiode and laser-diode optical arrows"
  ],
  "observedOptions": [
    "siunitx,RPvoltages"
  ],
  "notes": "Current implementation is a case-driven circuitikz subset, not the full circuitikz engine. The verified basic-bipoles fixture covers R/C, an independent V source, [american] internal +/- polarity, V< direction, siunitx unit labels, and RPvoltages reference polarity: American bipoles use +/- signs while European notation uses voltage arrows. DC dcvsource uses the native circle with two plates; dcisource separately paints its filled circle, angle-controlled pair of open arcs, shaft, and circuitikz currarrow. The manual's bipoles/dcisource/angle is read from \\ctikzset and local fill=... applies to both DC source bodies. Independent sV/sI plus vsourcesin/isourcesin and the named sinusoidal styles share the local four-cubic wave form, sources/scale, sources/symbol/thickness, numeric or auto sources/symbol/rotate, the sI external current label, and bipoles/isourcesin/angle's two-arc open outline. In American mode, a labelled sinusoidal voltage source such as sV=$V$ or csV=$g v_x$ now uses the native external +/- pair beneath its voltage label; l=$...$ remains a component label and intentionally adds no polarity. Independent sqV/tV plus vsourcesquare/vsourcetri and documented long names use the same source circle, exact native five-/three-segment waveform paths, thickness, and local/auto rotation. Controlled cV/cI, cvsource/cisource, and explicit EU/AM variants draw the native diamond exterior, its EU center line or AM internal signs/current arrow, and honor csources/scale. Controlled csV/csI plus cvsourcesin/cisourcesin and their documented aliases use that same diamond exterior with exact PGF sine/cosine cubics, csources/scale, csources/symbol/thickness, numeric or auto csources/symbol/rotate, external v/i labels, and no plain-source signs/arrow/line inside the sine diamond. The coefficients were reviewed from pgfcorepathconstruct.code.tex on 2026-08-06. The battery fixture verifies the default battery's four alternating plates, battery1's long/short pair with equal line width, battery2's three-times-thick short plate, default vertical leads, batteries/scale, and generic l= labels. L/vL select cute, American, or European bodies through explicit styles, tikzpicture style keys, or \\ctikzset{inductor=...}; documented inductors/scale, inductors/width, and inductors/coils are honored. \\ctikzset style changes now override inherited tikzpicture defaults. cute choke supports onelinechoke/twolineschoke and bipoles/cutechoke/cthick; named L/vL/choke elements expose core west/east with bipoles/inductors/core distance. Transformer core nodes honor the manual's transformer core/.cd style directory for relative thickness, color, and dash pairs; dash=default inherits the component pattern and dash=none creates an unbroken core. Their default cute body now follows the source's five wide and four return half-elliptical coils, full-height outer leads, the lead/coil/core line-width split, native core bounds, and the same derived coil span for named anchors. The diode fixtures verify D*/Do/sD*/leD* aliases, base D/sD/leD style aliases, zD/zDo/zD*, zzD/zzD-/zzD*, tvsD/tvsDo/tvsD*, and pD/pD*/pDo plus lasD/lasD*/lasDo; `diodes/scale`, `diodes/fill`, `l=` labels; Schottky cathode hooks; LED/photodiode/laser arrows; photodiode anode/cathode direction; local optical-arrow color/thickness; and the Zener/ZZener/TVS straight/sloped whisker switch. Tunnel, varcap, Shockley, bidirectional, tripole, and custom diode-shape families remain partial or unsupported. Custom transformer geometry, non-cute transformer styles, dot anchors, inductive sensors, source-specific fill defaults outside the DC subset, DC waveform sources, controlled square/triangular waveforms, custom no-v-symbol/plus/minus overrides, and the broader bipole catalog remain partial or unsupported."
};
