const BPMN_STYLES = String.raw`
\tikzset{
  every task/.style={},
  every gateway/.style={},
  every sequence/.style={},
  every message/.style={},
  every association/.style={},
  every event/.style={},
  every intermediate event/.style={},
  every token/.style={},
  every call activity/.style={},
  task/.style={rectangle,draw,minimum width=4em,minimum height=2em,rounded corners,align=center,every task,bpmn task},
  sequence/.style={->,every sequence,bpmn sequence},
  reverse sequence/.style={<-,every sequence,bpmn sequence},
  message/.style={->,dashed,every message,bpmn message},
  reverse message/.style={<-,dashed,every message,bpmn message},
  association/.style={densely dotted,every association,bpmn association},
  event/.style={circle,minimum width=1.5em,minimum height=1.5em,draw,every event,bpmn event},
  start event/.style={event},
  none start event/.style={start event},
  end event/.style={event,ultra thick},
  intermediate event/.style={event,double=white,every intermediate event},
  gateway/.style={diamond,draw,inner sep=0pt,minimum width=1.5em,minimum height=1.5em,align=center,every gateway,bpmn gateway},
  and gateway/.style={parallel gateway},
  parallel gateway/.style={gateway,label=center:\Large +},
  xor gateway/.style={exclusive gateway},
  exclusive gateway/.style={gateway,label=center:\Large\texttimes},
  or gateway/.style={inclusive gateway},
  inclusive gateway/.style={gateway,bpmn icon=inclusive},
  eventbased gateway/.style={gateway,bpmn icon=eventbased},
  message start event/.style={start event,bpmn icon=message},
  catching message intermediate event/.style={intermediate event,bpmn icon=message},
  throwing message intermediate event/.style={intermediate event,bpmn icon=message-fill},
  message end event/.style={end event,bpmn icon=message-fill},
  timer start event/.style={start event,bpmn icon=timer},
  timer event/.style={timer intermediate event},
  timer intermediate event/.style={intermediate event,bpmn icon=timer},
  signal start event/.style={start event,bpmn icon=signal},
  signal intermediate event/.style={catching signal intermediate event},
  catching signal intermediate event/.style={intermediate event,bpmn icon=signal},
  throwing signal intermediate event/.style={intermediate event,bpmn icon=signal-fill},
  signal end event/.style={end event,bpmn icon=signal-fill},
  terminate event/.style={end event,bpmn icon=terminate},
  error event/.style={throwing error end event},
  throwing error end event/.style={end event,bpmn icon=error},
  throwing compensation intermediate event/.style={intermediate event,bpmn icon=compensation},
  throwing compensation end event/.style={end event,bpmn icon=compensation-fill},
  boundary event/.style={circle,draw,fill=white,double=white,anchor=center,bpmn event},
  noninterrupting boundary event/.style={boundary event,dashed,dash pattern=on 1.5pt off 1pt},
  message boundary event/.style={boundary event,bpmn icon=message},
  timer boundary event/.style={boundary event,bpmn icon=timer},
  signal boundary event/.style={boundary event,bpmn icon=signal},
  compensation boundary event/.style={boundary event,bpmn icon=compensation},
  error boundary event/.style={boundary event,bpmn icon=error},
  subprocess/.style={task,inner sep=3mm,bpmn marker=subprocess},
  collapsed subprocess/.style={subprocess},
  expanded subprocess/.style={task,inner sep=3mm},
  call task/.style={task,thick,every call activity},
  call subprocess/.style={call task,inner sep=3mm,bpmn marker=subprocess,every call activity},
  collapsed call subprocess/.style={call subprocess},
  adhoc subprocess/.style={subprocess,bpmn marker=adhoc},
  collapsed adhoc subprocess/.style={adhoc subprocess},
  expanded adhoc subprocess/.style={expanded subprocess,bpmn marker=adhoc},
  multiinstance task/.style={task,bpmn marker=multiinstance},
  multiinstance subprocess/.style={subprocess,bpmn marker=multiinstance},
  collapsed multiinstance subprocess/.style={multiinstance subprocess},
  expanded multiinstance subprocess/.style={expanded subprocess,bpmn marker=multiinstance},
  loop task/.style={task,bpmn marker=loop},
  loop subprocess/.style={subprocess,bpmn marker=loop},
  collapsed loop subprocess/.style={loop subprocess},
  expanded loop subprocess/.style={expanded subprocess,bpmn marker=loop},
  compensation task/.style={task,bpmn marker=compensation},
  compensation subprocess/.style={subprocess,bpmn marker=compensation},
  collapsed compensation subprocess/.style={compensation subprocess},
  expanded compensation subprocess/.style={expanded subprocess,bpmn marker=compensation},
  manual task/.style={task,bpmn icon=manual},
  receive task/.style={task,bpmn icon=message},
  script task/.style={task,bpmn icon=script},
  send task/.style={task,bpmn icon=message-fill},
  service task/.style={task,bpmn icon=service},
  user task/.style={task,bpmn icon=user},
  pool/.style={draw,bpmn pool},
  pool label/.style={pool,bpmn icon=pool-label},
  data object/.style={draw,inner sep=0,minimum width=1em,minimum height=1.5em,bpmn icon=data-object},
  data collection/.style={data object,bpmn marker=multiinstance},
  data store/.style={draw,minimum width=1.4em,minimum height=1.6em,bpmn icon=data-store}
}
`;

export const tikzBpmnExtension = {
  name: "tikz-bpmn",
  phase: "preprocess",
  description: "Provides a pragmatic built-in subset of the tikz-bpmn style library.",
  commands: ["task", "event", "gateway", "sequence", "message", "association"],
  preprocess(source) {
    return `${BPMN_STYLES}\n${source}`;
  }
};
